### ISSUE TITLE
error on any ycombinator link on line 37

### ISSUE THREAD

**Issue by eicossa** [rmloveland/hn2org#1]
Deep recursion on subroutine "main::get_item_at_url" at ./hn2org [line 37](https://github.com/rmloveland/hn2org/blob/3f19e2798f25c111ec3d63f9493d6895ca49064b/hn2org#L37).

Perl version : 5.22
OS               : Antergos (Arch Linux)

**Comment by rmloveland** [comment]
Thanks - this should be fixed in commit dc2bff2dc2bff2 - I turned off recursion warnings for that subroutine.  Please feel-free to re-open if this issue persists.
